default:
  outputs:
    dev:
      type: duckdb
      path: "data/local.duckdb"
      threads: 8
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
      external_root: "data/datasets"
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
